{
 "title": "SE7/SE9 Grafana by prometheus",
 "tags": [
  "grafana",
  "prometheus"
 ],
 "time": { "from": "2026-02-23T15:10:22.199Z", "to": "2026-02-24T03:10:22.199Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "设备信息",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sophon_chip_info{app=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sophon_cpu_usage_percent{app=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "系统内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 * ( sophon_system_memory_used_bytes{app=\"prometheus\"} / sophon_system_memory_total_bytes{app=\"prometheus\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sophon_tpu_usage_percent{app=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPP使用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 12 },
   "targets": [
    {
     "expr": "sophon_vpp_usage_percent{app=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPU解码使用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sophon_vpu_dec_usage_percent{app=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPU编码使用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sophon_vpu_enc_usage_percent{app=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sophon_jpu_usage_percent{app=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "设备内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 * ( sophon_device_memory_used_bytes{app=\"prometheus\"} / sophon_device_memory_total_bytes{app=\"prometheus\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "设备内存使用率|TPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 * ( sophon_tpu_memory_used_bytes{app=\"prometheus\"} / sophon_tpu_memory_total_bytes{app=\"prometheus\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "设备内存使用率|VPP/VPSS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 * ( sophon_vpp_memory_used_bytes{app=\"prometheus\"} / sophon_vpp_memory_total_bytes{app=\"prometheus\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "设备内存使用率|VPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 * ( sophon_vpu_memory_used_bytes{app=\"prometheus\"} / sophon_vpu_memory_total_bytes{app=\"prometheus\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "功耗",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 30 },
   "targets": [
    {
     "expr": "sophon_power_usage_watts{app=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "温度(摄氏度)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sophon_chip_temperature_celsius{app=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "风扇转速",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 35 },
   "targets": [
    { "expr": "sophon_fan_speed_rpm", "legendFormat": "__auto" }
   ]
  }
 ]
}